Add extra dictionary support
postmodern/ffi-hunspell pull request #17
Opened 2016-11-16 06:01 UTC by cdchapman

**_Requires at least hunspell version 1.3.4_** see [the commit](https://github.com/hunspell/hunspell/commit/ee3bece2e6f92a03ceadd157fb51056a3bb9bf2d) when this interface was introduced. I don't know whether there is a way to attach the function only for specific versions of hunspell.

2016-11-16 17:51 UTC, cdchapman commented
A [similar situation](http://ffi.github.io/ruby-ffi-archive/messages/20110904-%5Bruby-ffi%5D%20attach_function%20a%20bit%20draconian-244.html) and [a workaround](http://ffi.github.io/ruby-ffi-archive/messages/20110904-%5Bruby-ffi%5D%20attach_function%20a%20bit%20draconian-244.html) came up in an early `ruby-ffi` discussion. I'll add another commit to use this approach.

2016-12-04 06:29 UTC, postmodern commented
When FFI attempts to bind a function that doesn't exist, it raises a `FFI::NotFoundError` exception. You could catch that when attaching the additional functions, and fail silently?

2017-07-27 18:07 UTC, Envek commented
@cdchapman, thank you, this is exactly functionality that I need!
@postmodern, what should be done yet in this PR to get it merged?

One more idea for ease of use is to make `add_dic` to search for dictionaries in `Hunspell.directories` as `FFI::Hunspell::Dict.open` method does to ease of adding other languages dictionaries.

My use case: I want to check words with russian, english and my custom dictionary (with my domain words).

For now with the code from this pull request I can do it as:

```rb
require 'ffi/hunspell'
dict = FFI::Hunspell.dict('ru_RU')
dict.add_dic('/usr/share/hunspell/en_US.dic') # ← I want it to be just en_US, I don't want to stick to any one path (which is differs between distros, etc)
dict.add_dic('/home/envek/evl.ms/ebay.ru/misc/hunspell.dic') # dxg/MS is here

# Usage:
dict.check?('собака'.encode(dict.encoding)) # => true
dict.check?('dog'.encode(dict.encoding)) # => true
dict.check?('dxg'.encode(dict.encoding)) # => true
```

I can continue work on this PR with your permission. WDYT?

2017-10-13 20:31 UTC, postmodern requested changes
Just define a place holder method and avoid any `method_missing` magic.

2017-10-13 20:31 UTC, postmodern commented on lib/ffi/hunspell/hunspell.rb
> +      define_singleton_method :method_missing do |symbol, *arguments, &block|
I would just define `Hunspell_add_dic` and have it raise `NotImplementedError`.

2017-10-13 20:32 UTC, postmodern commented
Sorry for the delay. Only one minor issue, but this looks ready to be merged.

2017-12-05 18:19 UTC, cdchapman commented
Hi @Envek. Sorry for the delay. It would not make sense to use the russian affix file, for example, with the `en_US` dictionary because the affixes for each language mean different things. Extra dictionaries reuse the affix file from the main dictionary. See hunspell/hunspell#348.

A better approach would be the following:

```ruby
require 'ffi/hunspell'
dict = FFI::Hunspell.dict('ru_RU')
dict = dict.add_dic('/full/path/to/russian_medical_words.dic') #

english_dict = FFI::Hunspell.dict('en_US')
english_dict.add_dic('/full/path/to/custom.dic') # dxg/MS is here

# Usage:
dict.check?('собака'.encode(dict.encoding)) # => true
dict.check?('полиглактином'.encode(dict.encoding)) # => true
english_dict.check?('dog'.encode(dict.encoding)) # => true
english_dict.check?('dxg'.encode(dict.encoding)) # => true
```
It is useful anyhow to know what language is being checked. An application could guess using some sort of heuristics, but it is good to be explicit about the guessing because it may choose the wrong dictionary.

2017-12-05 19:41 UTC, Envek commented
Yes, I figured that and finally I did exactly this: have two main dictionaries for every language and two additional dictionaries (one for each language).

But anyway this PR is still needed.

2019-10-25 02:27 UTC, merged

2019-10-25 02:32 UTC, postmodern commented
Been busy at work. Finally got around to working on ffi-hunspell. Merged and will be in 0.6.0.

2020-05-06 19:24 UTC, wynksaiddestroy commented
Is it possible by chance to release a new version to offer this new feature?